---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "hello-k8s"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hello-k8s"
  namespace: "hello-k8s"
  labels:
    app: "hello-k8s"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "hello-k8s"
  template:
    metadata:
      labels:
        app: "hello-k8s"
    spec:
      containers:
      - name: hello-k8s
        image: asia.gcr.io/talentia-poc/hello-k8s:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        env:
          - name: PG_SERVER
            value: "postgre-svc.default"
          - name: EUREKA_SERVER
            value: "eureka-svc.hello-k8s"
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports: already defined in each application
        #   - containerPort: 8080
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "hello-k8s-hpa-qtbb"
  namespace: "hello-k8s"
  labels:
    app: "hello-k8s"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "hello-k8s"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "hello-k8s-service"
  namespace: "hello-k8s"
  labels:
    app: "hello-k8s"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "hello-k8s"
  type: "LoadBalancer"
  loadBalancerIP: ""

